version: "3.8"
services:
  web:
    image: "node:16-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../:/home/node/app
    container_name: nodejs
    ports:
      - 9000:9000
    command: sh -c "npm install && npm run dev"
    environment:
      HOST: 0.0.0.0
